<?php
/**
 * Template: Smart Insight Notice
 *
 * المتغير المتاح هنا:
 *   $notice['html']  → نص الإشعار مع الأيقونة
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<div class="plinkly-smart-insight notice notice-info card fade-in">
	<?php
	// This HTML is safe and generated by Plinkly only, not user input.
	echo $notice['html'];
	?>
</div>

